config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users do
    get "collections", to: "collections#index"
    get "/rate_limit", to: "application#rate_limit", as: "rate_limit"
  end

  resources :collections do
    resources :organizations, shallow: true
    resources :projects, shallow: true
    get "issues" => "issues#index"
    member do
      get "embed"
    end
  end

  get ":id", to: 'collections#show', as: "short_collection"
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :organizations, dependent: :destroy
  has_many :projects, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  default_scope ->{ order('updated_at DESC') }

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, except: [:index, :new, :create]
  before_action :owner_only, only: [:edit, :update, :destroy, :add_issues]
  before_action :must_be_logged_in, only: [:new, :create]

  # GET /collections
  def index
    if params[:user_id]
      user = User.friendly.find(params[:user_id])
      @collections = user.collections
    else
      @collections = Collection.all
    end
  end

  # GET /collections/1
  def show
    get_help_wanted_issues(orgs: @collection.organizations, repos: @collection.projects, featured: @collection.featured_label)
  end

  def embed
    response.headers.delete "X-Frame-Options"
    get_help_wanted_issues(orgs: @collection.organizations, repos: @collection.projects)
    render layout: "embed"
  end

  # GET /collections/new
  def new
    @collection = Collection.new
    @project = Project.new
    @organization = Organization.new
  end

  # GET /collections/1/edit
  def edit
    @project = Project.new
    @organization = Organization.new
  end

  # POST /collections
  def create
    @collection = Collection.new(collection_params.merge(user: current_user))
    if @collection.save
      redirect_to @collection
    else
      render :new
    end
  end

  # PATCH/PUT /collections/1
  def update
    if @collection.update(collection_params)
      redirect_to @collection
    else
      render :edit
    end
  end

  # DELETE /collections/1
  def destroy
    @collection.destroy
    redirect_to collections_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.friendly.find params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :description, :featured_label, :slug)
    end

    def owner_only
      render json: {}, status: :forbidden unless current_user == @collection.user
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<div class="tile box is-child">

    <p class="title"><%= link_to collection.name, short_collection_path(collection) %></p>
    <p class="subtitle"><%= collection.description %></p>

    <p>
      By: <%= link_to user_path(collection.user.github_name) do %>
          <%= image_tag collection.user.image, class: "small-github-avatar" %> <%= collection.user.github_name %>
      <% end %>
    </p>

</div>

app/views/collections/_embed.html.erb
<% if @issues %>
  <% @issues.in_groups_of(3, false).each do |issues| %>
    <div class="tile is-12">
      <%= render issues %>
    </div>
  <% end %>
<% end %>

app/views/collections/_form.html.erb
<div class="box">
  <%= form_for @collection do |f| %>
    <% if @collection.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

        <ul>
        <% @collection.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name, class: "label" %>
      <p class="control">
        <%= f.text_field :name, class: 'input is-medium' %>
      </p>
    </div>

    <div class="field">
      <%= f.label :description, class: "label" %>
      <p class="control">
        <%= f.text_field :description, class: 'input is-medium' %>
      </p>
    </div>

    <div class="field">
      <%= f.label :featured_label, class: "label" %>
      <p class="control">
        <%= f.text_field :featured_label, class: 'input is-medium' %>
      </p>
    </div>

    <div class="field is-grouped">
      <p class="control">
        <%= f.submit 'Submit', class: 'button is-primary is-large' %>
      </p>
      <p class="control">
        <%= link_to 'Back', collections_path, class: 'button is-large' %>
      </p>
    </div>
  <% end %>
</div>

app/views/collections/edit.html.erb
<%= render 'form' %>

app/views/collections/embed.html.erb
<%= render 'embed' %>

app/views/collections/index.html.erb
<% if current_user %>
  <% content_for :title, "GitHub issues that need your help. 👏" %>
  <% content_for :action do %>
    <%= link_to "Create a new collection", new_collection_path, class: "button is-primary" %>
  <% end %>

  <% @collections.in_groups_of(2, false).each do |collection| %>
    <div class="tile is-12">
      <%= render collection %>
    </div>
  <% end %>
<% else %>
  <% content_for :title, "Login with GitHub and discover a thousand ways to help!" %>
  <% content_for :action do %>
    <%= link_to "Sign In", user_github_omniauth_authorize_path, class: "button is-primary" %>
  <% end %>
<% end %>

app/views/collections/new.html.erb
<% content_for :title, "Create a new collection" %>
<%= render 'form' %>

app/views/collections/show.html.erb
<%= content_for :title, @collection.name %>
<%= content_for :sub_title, @collection.description %>
<%= content_for :featured, @collection.featured_label %>

<% content_for :action do %>
  <div class="level">
    <div class="level-left">
      <% if @collection.user == current_user %>
        <%= link_to collection_projects_path(@collection), class: "button is-secondary level-item" do %>
          Add Projects &nbsp; <i class="fa fa-github" aria-hidden="true"></i>
        <% end %>
        <%= link_to edit_collection_path(@collection), class: "button is-secondary level-item" do %>
          Edit Collection &nbsp; <i class="fa fa-pencil" aria-hidden="true"></i>
        <% end %>
        <%= link_to @collection, class: "button is-secondary level-item", method: :delete, data: { confirm: 'Are you sure?' } do %>
          Remove Collection &nbsp; <i class="fa fa-trash" aria-hidden="true"></i>
        <% end %>
        <%= link_to embed_collection_path(@collection), class: "button is-secondary level-item" do %>
          Embed &nbsp; <i class="fa fa-external-link" aria-hidden="true"></i>
        <% end %>
      <% else %>
      <%= link_to collection_projects_path(@collection), class: "button is-secondary level-item" do %>
        See Projects &nbsp; <i class="fa fa-github" aria-hidden="true"></i>
      <% end %>
    <% end %>
</div>
  </div>
<% end %>

<%= render 'embed' %>