config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users do
    get "collections", to: "collections#index"
    get "/rate_limit", to: "application#rate_limit", as: "rate_limit"
  end

  resources :collections do
    resources :organizations, shallow: true
    resources :projects, shallow: true
    get "issues" => "issues#index"
    member do
      get "embed"
    end
  end

  get ":id", to: 'collections#show', as: "short_collection"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :collections, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable,
         :omniauthable

  extend FriendlyId
  friendly_id :github_name

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.provider = auth.provider
     user.uid = auth.uid
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     user.github_name = auth.info.nickname
     user.image = auth.info.image
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.friendly.find params[:id]
  end

  def destroy
    current_user.destroy
    redirect_to users_url
  end

end

app/views/users/_form.html.erb
<%= form_for @collection do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="box">

  <div class="media">
    <figure class="media-left">
      <%= link_to user.github_name do %>
        <%= image_tag user.image, class: 'large-github-avatar' %>
      <% end %>
    </figure>
    <div class="media-content">
      <p class="media-heading title"><%= link_to user.github_name, user %></p>
      <ul>
        <li>
          <%= link_to user_collections_path(user) do %>
            Collections <span class="tag"><%= user.collections.count %></span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>

  <% if current_user == user %>

    <hr />

    <footer class="level">
      <%= link_to new_collection_path, class: "button is-primary is-outlined level-item" do %>
        Create a new collection &nbsp; <i class="fa fa-plus" aria-hidden="true"></i>
      <% end %>
      <%= link_to current_user, class: "button is-primary is-outlined level-item", method: :delete, data: { confirm: "You sure?" } do %>
        Delete my account &nbsp; <i class="fa fa-trash" aria-hidden="true"></i>
      <% end %>
    </footer>

  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/users/index.html.erb
<%= render @users %>

app/views/users/new.html.erb
<h1>New Collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path, class: 'btn btn-default' %>

app/views/users/show.html.erb
<%= render @user %>