config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users do
    get "collections", to: "collections#index"
    get "/rate_limit", to: "application#rate_limit", as: "rate_limit"
  end

  resources :collections do
    resources :organizations, shallow: true
    resources :projects, shallow: true
    get "issues" => "issues#index"
    member do
      get "embed"
    end
  end

  get ":id", to: 'collections#show', as: "short_collection"
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :collection

  validates :url, presence: true, uniqueness: { scope: :collection, message: "can only add a project once per collection" }
  validates_format_of :url, with: /github\.com\/[a-zA-Z\-_0-9]+\/[a-zA-Z\-_0-9\.]+\/?/, on: :create

  default_scope -> { order(:url) }


  def full_name
    url.split("github.com/").last
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_collection, except: :destroy
  before_action :owner_only, only: [:destroy]
  protect_from_forgery :except => [:create]

  # GET /projects
  def index
  end

  # GET /projects/new
  def new
    @title = "Add a Project"
    @project = Project.new
    @collection = Collection.friendly.find(params[:collection_id])
  end

  # POST /projects
  def create
    @project = Project.create(project_params)
    if @project.errors.empty?
      redirect_to short_collection_path @collection
    else
      render :new
    end
  end

  # DELETE /projects/1
  def destroy
    project = Project.find(params[:id])
    project.destroy
    redirect_to short_collection_path project.collection
  end

  private

  def set_collection
    @collection = Collection.friendly.find(params[:collection_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:url, :collection_id)
  end

  def owner_only
    @project = Project.find(params[:id])
    render json: {}, status: :forbidden unless current_user == @project.collection.user
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for [@collection, @project] do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url, class: "label" do %>
    Add a GitHub repository
    <% end %>
    <p class="control is-expanded has-icons-left">
      <%= f.text_field :url, class: 'input is-expanded is-medium', placeholder: "https://github.com/ondrae/helpwanted", type: "url", required: true %>
      <span class="icon is-medium is-left">
        <i class="fa fa-github"></i>
      </span>
    </p>
  </div>

  <%= f.hidden_field :collection_id, value: @collection.id %>

  <div class="field is-grouped">
    <p class="control">
      <%= f.submit 'Submit', class: 'button is-primary is-large' %>
    </p>
    <p class="control">
    <%= link_to 'Back', collections_path, class: 'button is-large' %>
    </p>
  </div>

  <p>Wait a minute or two and the issues will start showing up.</p>
<% end %>

app/views/projects/index.html.erb
<% if @collection.user == current_user %>
  <%= content_for :title, "Add projects" %>
  <%= content_for :sub_title, "Choose GitHub organizations and projects to pull the issues from." %>

  <% content_for :action do %>
    <div class="level">
      <div class="level-left">
        <%= link_to new_collection_organization_path(@collection), class: "button is-primary level-item" do %>
          Add a GitHub Organization &nbsp; <i class="fa fa-github" aria-hidden="true"></i>
        <% end %>
        <%= link_to new_collection_project_path(@collection), class: "button is-primary level-item" do %>
          Add a GitHub Project &nbsp; <i class="fa fa-github" aria-hidden="true"></i>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  <%= content_for :title, @collection.name %>
  <%= content_for :sub_title, @collection.description %>
<% end %>

<% if @collection.organizations or @collection.projects %>
  <p>Organizations & Projects included:</p>
  <ul>
    <% @collection.organizations.each do |org| %>
      <li>* <%= org.url %></li>
    <% end %>
    <% @collection.projects.each do |project| %>
      <li>* <%= project.url %></li>
    <% end %>
  </ul>
<% end %>