config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users do
    get "collections", to: "collections#index"
    get "/rate_limit", to: "application#rate_limit", as: "rate_limit"
  end

  resources :collections do
    resources :organizations, shallow: true
    resources :projects, shallow: true
    get "issues" => "issues#index"
    member do
      get "embed"
    end
  end

  get ":id", to: 'collections#show', as: "short_collection"
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :collection
  validates :url, presence: true, uniqueness: { scope: :collection, message: "can only add an organization once per collection" }
  validates_format_of :url, with: /github\.com\/[a-zA-Z\-_0-9]+/, on: :create

  default_scope -> { order(:url) }

  def name
    url.split("github.com/").last
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_collection, except: :destroy
  before_action :owner_only, only: [:destroy]
  protect_from_forgery :except => [:create]

  # GET /organizations
  def index
    @organizations = @collection.organizations
  end

  # GET /organizations/new
  def new
    @title = "Add a organization"
    @organization = Organization.new
    @collection = Collection.friendly.find(params[:collection_id])
  end


  def create
    @organization = Organization.create(organization_params)
    if @organization.errors.empty?
      redirect_to short_collection_path @collection
    else
      render :new
    end
  end

  # DELETE /organizations/1
  def destroy
    organization = Organization.find(params[:id])
    organization.destroy
    redirect_to short_collection_path organization.collection
  end

  private

  def set_collection
    @collection = Collection.friendly.find(params[:collection_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def organization_params
    params.require(:organization).permit(:url, :collection_id)
  end

  def owner_only
    @organization = Organization.find(params[:id])
    render json: {}, status: :forbidden unless current_user == @organization.collection.user
  end
end

app/views/organizations/_form.html.erb
<%= form_for [@collection, @organization] do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url, class: "label" do %>
      Add a GitHub organization
    <% end %>
    <p class="control is-expanded has-icons-left">
      <%= f.text_field :url, class: 'input is-expanded is-medium', placeholder: "https://github.com/codeforamerica", type: "url", required: true %>
      <span class="icon is-medium is-left">
        <i class="fa fa-github"></i>
      </span>
    </p>
  </div>

  <%= f.hidden_field :collection_id, value: @collection.id %>

  <div class="field is-grouped">
    <p class="control">
      <%= f.submit 'Submit', class: 'button is-primary is-large' %>
    </p>
    <p class="control">
    <%= link_to 'Back', collections_path, class: 'button is-large' %>
    </p>
  </div>
<% end %>

app/views/organizations/_project.html.erb
<div class="box">

  <header>
    <p class="title"><%= link_to project.name, project.url %></p>
    <p class="subtitle"><%= project.description %></p>
  </header>

  <hr />

  <div class="level is-mobile">
    <%= link_to "https://github.com/" + project.owner_login, class: "level-item" do %>
        <%= image_tag project.owner_avatar_url, class: "small-github-avatar" %> <%= project.owner_login %>
    <% end %>
    <%= link_to project.collection, class: "level-item" do %>
        <%= project.collection.name %>
    <% end %>
  </div>


  <% if current_user == project.collection.user %>

    <footer class="level">
      <%= link_to project, class: "button is-primary is-outlined level-item", method: :delete, data: { confirm: 'Are you sure?' } do %>
        Remove Project &nbsp; <i class="fa fa-trash" aria-hidden="true"></i>
      <% end %>
    </footer>

  <% end %>

</div>

app/views/organizations/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/organizations/index.html.erb
<% content_for :title, "#{@collection.name} Projects" %>
<% content_for :sub_title, "Hand picked Github projects" %>
<% if user_signed_in? %>
  <% content_for :action do %>
    <% link_to 'Add a project &nbsp; <i class="fa fa-plus" aria-hidden="true"></i>'.html_safe, new_collection_project_path, class: "button is-primary" %>
  <% end %>
<% end %>
<%= render @projects %>

app/views/organizations/new.html.erb
<%= render 'form' %>